version: '3.8'

services:
  accrual:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=accrual
    container_name: accrual
    env_file:
      - .env
    environment:
      - SERVICE_NAME=accrual
      - RUN_ADDRESS=0.0.0.0:8080
    command: ./accrual
    ports:
      - 8081:8080
    depends_on:
      - database

  gophermart:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=gophermart
    container_name: gophermart
    env_file:
      - .env
    environment:
      - SERVICE_NAME=gophermart
      - RUN_ADDRESS=0.0.0.0:8080
      - ACCRUAL_SYSTEM_ADDRESS=accrual
    command: ./gophermart
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    container_name: postgres16
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: