# Документация https://taskfile.dev/
version: "3"

dotenv:
  - .env # Должен быть файл .env Где указаны нужные переменные окружения

tasks:
  statictest:
    cmds:
      - go vet -vettool=./statictest ./...
  statictest-win:
    cmds:
      - go vet -vettool=./statictest.exe ./...
  migration-up:
    cmds:
      - migrate -path internal/storage/migrations -database postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable up
  migration-up-1:
    cmds:
      - migrate -path internal/storage/migrations -database postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable up 1
  migration-down-1:
    cmds:
      - migrate -path internal/storage/migrations -database postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable down 1
  migration-drop:
    cmds:
      - migrate -path internal/storage/migrations -database postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable drop
  build:
    cmds:
      - "go build -o cmd/accrual/accrual cmd/accrual/main.go"
      - "go build -o cmd/gophermart/gophermart cmd/gophermart/main.go"
  run:
    cmds:
      - go run cmd/gophermart/main.go
  swag:
    cmds:
      - swag init -g ./cmd/gophermart/main.go