# Документация https://taskfile.dev/
version: "3"

dotenv:
  - .env # Должен быть файл .env Где указаны нужные переменные окружения

tasks:
  statictest:
    cmds:
      - go vet -vettool=./statictest ./...
  migration-up:
    cmds:
      - migrate -path migrations -database postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable up
  migration-up-1:
    cmds:
      - migrate -path migrations -database postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable up 1
  migration-down-1:
    cmds:
      - migrate -path migrations -database postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable down 1
  migration-drop:
    cmds:
      - migrate -path migrations -database postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable drop
  build:
    cmds:
      - ""