# Документация https://taskfile.dev/
version: "3"

dotenv:
  - .env # Должен быть файл .env Где указаны нужные переменные окружения

vars:
  migrdirG: internal/storage/gophermart/migrations
  migrdirA: internal/storage/accrual/migrations
tasks:
  statictest:
    cmds:
      - go vet -vettool=./statictest ./...
  statictest-win:
    cmds:
      - go vet -vettool=./statictest.exe ./...
  mg-up:
    cmds:
      - migrate -path {{.migrdirG}} -database postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable up
  mg-up-1:
    cmds:
      - migrate -path {{.migrdirG}} -database postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable up 1
  mg-down-1:
    cmds:
      - migrate -path {{.migrdirG}} -database postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable down 1
  mg-drop:
    cmds:
      - migrate -path {{.migrdirG}} -database postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable drop
  ma-up:
    cmds:
      - migrate -path {{.migrdirA}} -database postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME_ACC?sslmode=disable up
  ma-up-1:
    cmds:
      - migrate -path {{.migrdirA}} -database postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME_ACC?sslmode=disable up 1
  ma-down-1:
    cmds:
      - migrate -path {{.migrdirA}} -database postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME_ACC?sslmode=disable down 1
  ma-drop:
    cmds:
      - migrate -path {{.migrdirA}} -database postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME_ACC?sslmode=disable drop
  # OTHER
  build:
    cmds:
      - "go build -o cmd/accrual/accrual cmd/accrual/main.go"
      - "go build -o cmd/gophermart/gophermart cmd/gophermart/main.go"
  run:
    cmds:
      - go run cmd/gophermart/main.go
  swag:
    cmds:
      - swag init -g ./cmd/gophermart/main.go -o docs/gophermart
      - swag init -g ./cmd/accrual/main.go -o docs/accrual 