BEGIN;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    login VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(64) NOT NULL,
    balance DECIMAL(10, 2) DEFAULT 0 NOT NULL 
);

CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    number VARCHAR(255) UNIQUE NOT NULL,
    status VARCHAR(50) DEFAULT 'NEW' NOT NULL CHECK (status IN ('NEW', 'PROCESSING', 'INVALID', 'PROCESSED')),
    accrual BIGINT DEFAULT 0 NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_login VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_login) REFERENCES users(login)
);

COMMIT;